name: pipeline

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Build-latex
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex
          working_directory: image/cv/
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build img and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./files/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/resumewebserver:latest
